POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbGxvMiIsImlkIjoiNjhkYmZkN2MwYzkwNmI2ZTE1YWJmZWI4IiwiaWF0IjoxNzU5MjQ3ODExfQ.4nMgfAdV5venTPVM5-YK1kVBT7MlbNbUKEllAZw3IR8

{
    "title" : "2",
    "author" : "3",
    "url" : "3",
    "likes" : 3,
    "userId":"68daaa2957f66f81e6e3df79"
}